# ===============================
# Application
# ===============================
spring.application.name=page-pulse

# ===============================
# Server
# ===============================
server.port=${PORT:8080}

# ===============================
# MySQL Database
# ===============================
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Remove this line because Hibernate 6 detects it automatically
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# CORS
# ===============================
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

# ===============================
# Jsoup
# ===============================
app.jsoup.timeout=15000
app.jsoup.user-agent=Mozilla/5.0 (compatible; PagePulseBot/1.0)
app.jsoup.follow-redirects=true
app.jsoup.max-body-size=5242880

# ===============================
# Logging
# ===============================
logging.level.com.pagepulse=DEBUG
logging.level.org.springframework.web=INFO